### ISSUE TITLE
Set up Docsify instance

### ISSUE THREAD

**Issue by space-fwog** [Then-We-Win/tww-app#112]
Create a "docs" folder in the root of this repo, install Docsify and begin adding content (logo, name, basic description, etc).

This is their documentation, which will teach you how to do that :) https://docsify.js.org/#/

This docs site will be mostly troubleshooting/terms/developer docs, etc. This should be the general inspiration for planning out the menu.

**Comment by samdeskin** [comment]
Then We Win Content Policy
Then We Win is a network of campaigns that are created, run, and populated by you, the Then We Win users.
Through these communities, you can post, comment, discuss, learn, debate, support, and connect with people who share your interests, and we encourage you to find your home on Then We Win.
While not every campaign may be for you, no campaign should be used as a weapon. We are an organization that prides itself of peacefully achieving our objectives. Campaigns should create a sense of belonging for their members, not try to diminish it for others. Likewise, everyone on Then We Win should have an expectation of privacy and safety, so please respect the privacy and safety of others.
Every campaign on Then We Win is defined by its users. Some of these users help manage the campaign. The culture of each campaign is shaped these rules and through discussions of its campaign members. Please abide by these rules and do not interfere with those in which you are not a member.
The platform-wide rules apply to everyone on Then We Win. These rules are enforced by us, the admins.
Then We Win and its campaigns are only what we make of them together, and can only exist if we operate by a shared set of rules. We ask that you abide by not just the letter of these rules, but the spirit as well.
Rules
Rule 1
Remember we are all human. Then We Win is a place for creating campaigns and belonging, not for attacking marginalized or vulnerable groups of people. Everyone has a right to use Then We Win free of harassment, bullying, and threats of violence. Campaigns and users that incite violence or that promote hate based on identity or vulnerability will be banned.
Rule 2
Abide by campaign rules. Participate honestly into campaigns where you have a personal interest, and do not engage in practices that interfere with or disrupt Then We Win campaigns.
Rule 3
Respect the privacy of others. Instigating harassment, for example by revealing someone’s personal or confidential information, is not allowed. No campaign or its members may ever seek or threaten to seek intimate or sexually-explicit media of anyone.
Rule 4
Do not seek or encourage seeking sexual or suggestive content involving minors. Anything having to do with minors are off limits in any campaign.
Rule 5
You don’t have to use your real name to use Then We Win, but don’t impersonate an individual or an entity in a misleading or deceptive manner.
Rule 6
Ensure people have predictable experiences on Then We Win by properly labeling content and campaigns.
Rule 7
Keep it legal, and avoid doing anything illegal or soliciting anything illegal to be done.
Rule 8
Don’t break the site or do anything that interferes with normal use of Then We Win.
Enforcement
We have a variety of ways of enforcing our rules, including, but not limited to
Asking you nicely to knock it off
Asking you less nicely
Temporary or permanent suspension of accounts
Removal of privileges from, or adding restrictions to, accounts
Adding restrictions to Then We Win campaigns
Removal of content
Banning of Then We Win campaigns

**Comment by samdeskin** [comment]
Sorry ... learning how this works.
