### ISSUE TITLE
Page: Login

### ISSUE THREAD

**Issue by onexdata** [Then-We-Win/tww-app#14]

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $10.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://app.gitcommits.com/issue/page-login).
- Questions? Checkout [GitCommits Help](https://www.gitcommits.com/faq)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
@onexdata Any questions I can answer for you about GitCommits and how this should be working for you?  Please let me know if I can help in any way.  Thanks!

**Comment by onexdata** [comment]
Part of the initial commit
